### Variables
@gateway = https://n4nrvecypi.execute-api.us-east-1.amazonaws.com/prod
@token = PEGA_AQUI_TU_ACCESS_TOKEN

### Crear pedido
POST {{gateway}}/api/v1/pedidos
Authorization: Bearer {{token}}
Content-Type: application/json

[
    {
        "nombreProducto": "Leche",
        "cantidad": 2
    },
    {
        "nombreProducto": "Pan",
        "cantidad": 1
    },
    {
        "nombreProducto": "Huevos",
        "cantidad": 12
    }
]

###

### Obtener todos los pedidos
GET {{gateway}}/api/v1/pedidos
Authorization: Bearer {{token}}

###

### Eliminar todos los pedidos
DELETE {{gateway}}/api/v1/pedidos/all
Authorization: Bearer {{token}}

###