### Crear pedido
POST http://localhost:8081/api/v1/pedidos
Authorization:
Content-Type: application/json

[
    {
        "nombreProducto": "Leche",
        "cantidad": 2
    },
    {
        "nombreProducto": "Pan",
        "cantidad": 1
    },
    {
        "nombreProducto": "Huevos",
        "cantidad": 12
    }
]

###

### Obtener todos los pedidos
GET http://localhost:8081/api/v1/pedidos
Authorization:

###

### Eliminar todos los pedidos
DELETE http://localhost:8081/api/v1/pedidos/all
Authorization: