server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?ssl=true&sslmode=require&pgbouncer=true
        username: postgres.myunbjgdvtkkvgaqemwz
        password: oeyA3CqStCq0LwHx
        driver-class-name: org.postgresql.Driver
    application:
        name: pedidos-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://login.microsoftonline.com/1f3a849e-c198-4ff7-b67c-d17f15cbc152/v2.0