server:
    port: ${SERVER_PORT}

spring:
    datasource:
        url: ${DATABASE_URL}
        username: ${PEDIDOS_DB_USER}
        password: ${PEDIDOS_DB_PASS}
    application:
        name: pedidos-service
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        open-in-view: false